### ISSUE TITLE
Output a JSON file for contile to consume

### ISSUE THREAD

**Issue by taddes** [mozilla-services/consvc-shepherd#104] opened 2023-04-25 21:49 UTC
We want Shepherd to produce a JSON file that gets sent to the Contile bucket.

Note there’s a dependency on [this PR](https://github.com/mozilla-services/consvc-shepherd/pull/96/files)

This requires:
- Validate allocation schema in `test_schema.py`
- Adding to_dict method in the AllocationSetting Model
- Adding to_dict method in the PartnerAllocation Model
-  An admin action similar to [the publish snapshot action](https://github.com/mozilla-services/consvc-shepherd/blob/main/consvc_shepherd/admin.py#L12)* to publish new allocation settings.
- Admin validation and construction of object to then be output as JSON
-  Added tests to test our new JSON schema for allocation
* We may want to move this into the /allocation page, but lets have it as an admin action for now

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-2367)

**Comment by data-sync-user** [comment] 2023-05-05 17:23
➤ Taddes Korris commented:

Data sync duplicate of https://mozilla-hub.atlassian.net/browse/DISCO-2310 ( https://mozilla-hub.atlassian.net/browse/DISCO-2310|smart-link )

**Closed** 2023-05-05 17:39 UTC
